name: Lint

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Running lint
      run: |
          echo "Linting..."
          npm run prepare
