name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running lint
      run: |
          echo "Installing modules"
          npm i
          echo "Linting..."
          npm run prepare
