name: CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running lint
      run: |
          echo "Installing modules"
          npm i
          echo "Linting..."
          npm run prepare  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Runt test
      run: |
          echo "Installing modules"
          npm i
          echo "Running tests"
          npm run test
