name: CD/CI

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    name: Install modules
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: |
          echo "Installing modules"
  lint:
    name: Run Lint
    needs: init
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run lint
      run: |
        echo "Linting..."
        npm run prepare
  test: 
    name: Run Test
    needs: init
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        echo "Linting..."
        npm run test
