name: CD/CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run npm install
      run: |
          echo "Installing modules"
          npm i
    - name: Run lint
      run: |
          echo "Linting..."
          npm run prepare  
          
    - name: Runt test
      run: |
          echo "Running tests"
          npm run test
